"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
[](fg:grey bg:black)\
$directory\
[](fg:grey bg:black)\
$git_branch\
$git_status\
[](fg:grey bg:black)\
$conda\
[](fg:grey bg:black)\
$cmd_duration\
[](fg:grey bg:black)\
$time\
[](fg:black)\
$status\
$line_break$character"""

palette = 'tejas'

[palettes.tejas]
black = '#000000'
grey = '#656565'
red = '#e46d63'
brown = '#ce9178'
yellow = '#e9e64d'
green = '#58c18f'
white = '#eaeaea'
aqua = '#60c1de'
blue = '#77abd9'
magenta = '#d38dd9'

[os]
disabled = false
style = "bg:black fg:white"

[username]
show_always = true
style_user = "bg:black fg:brown"
style_root = "bg:black fg:brown"
format = '[ $user ]($style)'

[directory]
style = "fg:blue bg:black"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = ""

[git_branch]
style = "bg:black"
format = '[[ $branch ](fg:green bg:black)]($style)'

[git_status]
ahead = '⇡$ahead_count '
behind = '⇣$behind_count '
diverged = '⇕ ⇡$ahead_count ⇣$behind_count '
conflicted = '=$count '
untracked = '?$count '
stashed = '*$count '
modified = '!$count '
staged = '+$count '
renamed = '»$count '
deleted = '✘$count '
style = 'bg:black '
format = '[[($all_status$ahead_behind)](fg:green bg:black)]($style)'

[nodejs]
style = "bg:black"
format = '[[ $symbol( $version) ](fg:aqua bg:black)]($style)'

[c]
style = "bg:black"
format = '[[ $symbol( $version) ](fg:aqua bg:black)]($style)'

[rust]
style = "bg:black"
format = '[[ $symbol( $version) ](fg:aqua bg:black)]($style)'

[golang]
style = "bg:black"
format = '[[ $symbol( $version) ](fg:aqua bg:black)]($style)'

[php]
style = "bg:black"
format = '[[ $symbol( $version) ](fg:aqua bg:black)]($style)'

[java]
style = "bg:black"
format = '[[ $symbol( $version) ](fg:aqua bg:black)]($style)'

[kotlin]
style = "bg:black"
format = '[[ $symbol( $version) ](fg:aqua bg:black)]($style)'

[haskell]
style = "bg:black"
format = '[[ $symbol( $version) ](fg:aqua bg:black)]($style)'

[docker_context]
style = "bg:black"
format = '[[ $symbol( $context) ](fg:aqua bg:black)]($style)'

[conda]
style = "bg:black"
ignore_base = false
format = '[[ $symbol( $environment) ](fg:aqua bg:black)]($style)'

[time]
disabled = false
time_format = "%T"
style = "bg:black"
format = '[[ $time ](fg:white bg:black)]($style)'

[line_break]
disabled = false

[cmd_duration]
min_time = 0
show_milliseconds = true
style = "bg:black fg:yellow"
format = '[ ⏱ $duration ]($style)'

[status]
disabled = false
symbol = '[✘](fg:red)'
success_symbol = '[✔](fg:green)'
style = "fg:red"
format = '[ $symbol $common_meaning$signal_name$maybe_int ]($style)'
recognize_signal_code = true
pipestatus = true
pipestatus_separator = '[|](fg:grey)'
pipestatus_format = '[$pipestatus]($style)'
